# RP Stories for Starlifter Terminal — uses {cargo_type} placeholder
# LOW (0-9), MEDIUM (10-19), HIGH (20-29) severity

stories = [
    # ── LOW SEVERITY (0-9) ──
    'Loading operations completed without a single registry error. Under the eye of Loading Officer {officer}, the deck crew aligned every {cargo_type} container onto the cargo grid of the {ship}. Captain {captain}, magnetic locks are drawing stable power. Mass distribution optimized. The hangar crew led by {crew} has cleared the pad. You are cleared for pre-flight engine spool. May your quantum travel be smooth.',
    'Shipping manifest officially locked and transmitted to UEE Fleet Command. Loading crew {crew} reports textbook grid alignment on the {ship}. All external loading arms for the {cargo_type} cargo fully retracted. Captain {captain}, flight path looks completely clear. Dock master has cleared your launch window. Have a safe journey, Captain.',
    'Smooth standard military loading cycle finalized. No cargo discrepancies detected on the {ship}. Every {cargo_type} crate was logged, scanned, and secured under {officer}. The team {crew} ensured perfect balance for quantum transition. Captain {captain}, manifest signed, sealed, and uploaded to the 44th Battle Group database. Safe travels.',
    'Navy dock workers finished stacking the final {cargo_type} containers into the hold on the {ship}. Crew {crew} has cleared the deck. Officer {officer} confirms all magnetic clamps active. Captain {captain}, cargo stable even during high-G maneuvers. Flight clearance sent to HUD. Clear the landing pad at your convenience.',
    'Cargo bay of the {ship} is officially loaded, sealed, and pressurized. Officer {officer} supervised the process. The {cargo_type} cargo placed into grid slots by crew {crew}. Environmental controls at Navy baseline. Captain {captain}, exterior doors fully locked. Launch pad is clear. Fly safe.',
    'Routine manifest upload verified by the 44th Battle Group. The {cargo_type} haul on the {ship} was inspected by Loading Officer {officer}. Every container checked for barcode readability. Crew {crew} completed staging ahead of schedule. Captain {captain}, no hazardous materials detected. Cleared to launch.',
    'All {cargo_type} cargo on the {ship} safely stacked and checked for stability. The team under {crew} completed their final sweep. Officer {officer} reports all tie-downs and nets properly tensioned. Captain {captain}, nominal thruster response expected during atmospheric ascent. Safe flight.',
    'Pre-flight cargo manifest officially signed off. Every item in this {cargo_type} shipment matches UEE Navy guidelines. Officer {officer} reports zero staging delays on the {ship}. Crew {crew} handled all crates with care. Captain {captain}, departure corridor bravo assigned. Clear the pad when ready.',
    'Ship cargo grid fully active, balanced, and locked down. Every {cargo_type} container on the {ship} has cleared Navy security scanners. Staged by {crew} and approved by {officer}. Captain {captain}, manifest visible on all security databases. Docking clamps release on VTOL spool. Have a safe quantum jump.',
    'Manifest officially locked, external loading arms disconnected from the {ship}. Hold fully secured for quantum travel with {cargo_type} cargo. Officer {officer} completed the final walk-through. Crew {crew} has cleared the hangar. Captain {captain}, cargo perfectly centered for optimal fuel efficiency. Fly safe, Captain.',

    # ── MEDIUM SEVERITY (10-19) ──
    'Cargo secured, but must issue a warning, Captain {captain}. Navy intel reports a spike in Nine Tails activity along quantum lanes near the {ship}. Officer {officer} recommends powering up shields immediately. Crew {crew} worked under elevated protocols to load {cargo_type} cargo quickly. Outlaw scouts may be monitoring departure vectors. Stay sharp.',
    'Loading complete, but we found a hitch during inspection. While crew {crew} was moving the last {cargo_type} container on the {ship}, they noticed a minor hydraulic fluid leak near the thruster gimbal. Officer {officer} suspects worn seals. Fluid topped off but monitor component wear via MFD. Shield generator running slightly hot. Fly with caution, Captain {captain}.',
    'Bureaucratic headache on the pad today, Captain {captain}. Customs officers flagged two {cargo_type} containers for contraband inspection on the {ship}. Officer {officer} sorted the paperwork but the delay threw off the schedule. Crew {crew} had to rush final mag-lock checks. Double-check cargo grid diagnostics once you clear atmosphere.',
    'Freight on the {ship} is secured, but some local raiders spray-painted graffiti across your hull. Crew {crew} tried to scrub it off. Officer {officer} notes no flight impact but proximity sensors are partially blocked. Fly carefully, Captain {captain}.',
    'We loaded the {cargo_type} units onto the {ship}, but sensors are throwing a yellow warning. During grid locking, the power relay connected to the secondary cooler experienced a voltage spike. Crew {crew} checked fuses — intact but cooler running at reduced efficiency. Officer {officer} warns hold temperature might rise during quantum drive. Proceed with caution, Captain {captain}.',
    'Cargo manifest for the {ship} is signed, but we hit an avionics bus issue during upload. While {officer} was sync-logging, the Navy data link suffered a blackout. Crew {crew} had to reset the data port three times. Nav computer might take longer to calculate quantum vectors. Starboard thruster showing 5% deficit. Stay alert, Captain {captain}.',
    'Pre-flight check on the {ship} completed, but atmospheric hazard warning issued, Captain {captain}. Weather satellites report an ion storm in the upper stratosphere. Officer {officer} urges adjusting ascent angle. Crew {crew} secured extra straps over the {cargo_type} containers to prevent vibrations. Ship shields will cycle rapidly through the cloud layer.',
    'Cargo grid locked down, but we detected a suspicious vibration from the cargo ramp hinge on the {ship}. Crew {crew} found a hairline fracture in the lower locking pin. Officer {officer} believes it can survive this transit but avoid high-G reentry. Ramp locked manually from outside. Fly safe, Captain {captain}.',
    'Ship {ship} is packed, but there is a security advisory. Local miners protesting near the hangar. Crew {crew} closed hangar doors early. Officer {officer} confirmed no physical damage, but someone disconnected the fuel intake cap. Re-secured, but verify hydrogen fuel levels, Captain {captain}. Clear the pad quickly.',
    'All {cargo_type} containers logged on the {ship}, but life support scrubbers running on secondary backup. Officer {officer} noticed the primary O2 filter was clogged with industrial dust. Crew {crew} had no spare filter. Auxiliary system depletes faster with personnel aboard. Debris fields reported along secondary trade lanes, Captain {captain}.',

    # ── HIGH SEVERITY (20-29) ──
    'Nightmare in the hangar bay, Captain {captain}. During final staging for the {ship}, a cargo crane suffered catastrophic gravity generator failure. A {cargo_type} container broke loose and fell onto the deck, causing an electrical fire. Two crew {crew} members sustained severe flash burns. Officer {officer} reports structural damage to the grid. Emergency straps in use. Ship off-balance. Nine Tails blockading the orbital exit. Godspeed.',
    'Emergency loading protocols on the {ship} while the station was taking fire. Hangar doors damaged by XenoThreat raid. Officer {officer} bypassed safety scans for immediate departure. Crew {crew} worked in terror as explosions shook the hangar. The {cargo_type} containers thrown onto the grid — weight distribution not guaranteed. Captain {captain}, get off this pad immediately. Jump to nearest safe point. Run now.',
    'Critical failure during staging for the {ship}. A volatile container ruptured, leaking toxic gas into the lower hold. Crew {crew} donned hazmat gear, vented the bay, and sealed the leaking {cargo_type} crate. Officer {officer} reports environmental sensors glitching. Toxic vapor lingering — keep suit pressurized. GrimHEX Raiders closing in. Cargo grid barely holding power. Extreme risk conditions, Captain {captain}.',
    'Severe accident on the landing pad during final alignment. A structural beam collapsed under a {cargo_type} container, pinning a crew member. Officer {officer} reports area cleared by emergency services, but crew {crew} is in shock. Loading halted halfway — manifest incomplete. Cargo grid unbalanced — flight computer throwing warnings. Recalibrate thrusters before breaking orbit, Captain {captain}.',
    'Absolute disaster, Captain {captain}. Nine Tails blockade established outside the armistice zone. Crew {crew} panic-loaded the {ship}. Officer {officer} forced to sign off on sub-optimal {cargo_type} cargo layout. Magnetic locks failing. Quantum risks losing half the haul. Pirate interdictors pulling ships out of warp. Brace for impact.',
    'Severe hangar incident — tractor beam malfunction caused three {cargo_type} crates to break loose on the {ship}, smashing into magnetic locks. Officer {officer} patched the power grid. Crew {crew} used steel cables to hold damaged crates. Rear ramp bent — may not hold atmospheric pressure. Captain {captain}, monitor cargo bay pressure. XenoThreat raiders patrolling. Ship damaged and vulnerable.',
    'Alert: Cargo hold of the {ship} sustained explosive damage during loading. Ammunition chain reaction shook the hangar. Crew {crew} sustained casualties. Officer {officer} reports grid only partially functional — relays sparking under {cargo_type} weight. Loading aborted — containers unsecured. Captain {captain}, escape immediately before structural collapse.',
    'Emergency manifest issued under worst conditions. Station power grid failed mid-load. Crew {crew} worked in darkness using manual systems. Officer {officer} warns at least two {cargo_type} containers are unverified and may contain hazardous materials. Crates misaligned. Comms jammed. Captain {captain}, flying blind with dangerous load. Spool quantum drive immediately.',
    'Catastrophic loading shift — the {ship} is in a dangerous state. Ramp hydraulic system failed under a {cargo_type} container, injuring two workers and causing fire. Temporary braces installed by {crew}. Officer {officer} sealed compromised sections. Rear ramp critically compromised — do not open during transit. Captain {captain}, launch immediately before fires reach fuel lines.',
    'Final warning, Captain {captain}. Station entering full lockdown — incoming XenoThreat fleet. Pirate bombers targeting landing pads. Officer {officer} signed manifest remotely while evacuating. Crew {crew} abandoned remaining {cargo_type} cargo — ship partially loaded and unbalanced. Bay doors jammed open. Launch now. Do not follow standard vectors — punch the throttle and ghost the sector. Good luck, Captain.'
]
